### ISSUE TITLE
Inconsistent Behavior and Errors with hatchet.api.eventCreate (REST API) vs hatchet.events.push (gRPC)

### ISSUE THREAD

**Issue by AmoonPod** [hatchet-dev/hatchet#1542]
We are observing inconsistent behavior and errors when attempting to trigger Hatchet events using the REST API (hatchet.api.eventCreate) compared to using the gRPC interface (hatchet.events.push).

### Observed Behavior:

- **Using hatchet.api.eventCreate (REST API):**

  - Event triggers often result in a 500 Internal Server Error being logged in the client-side console where the event is triggered.
  - Despite the logged error, the corresponding workflow sometimes appears to start and run correctly, visible in the Hatchet dashboard.
  - However, the 500 error is not just a logging artifact. In some cases, after encountering this error, subsequent attempts to trigger any event (even different event keys) using hatchet.api.eventCreate seem to fail silently or are significantly delayed, suggesting the error might be causing instability or blocking further API interactions temporarily.

- **Using hatchet.events.push (gRPC):**

  - Events are triggered reliably and consistently.
  - No errors are logged in the client-side console.
  - Workflows reliably appear in the Hatchet dashboard and execute as expected.

### Expected Behavior:
The hatchet.api.eventCreate method should function as reliably as hatchet.events.push. It should:

1. Successfully trigger the event and corresponding workflow without client-side errors.
2. Not return a 500 Internal Server Error when the event is accepted.
3. Consistently allow subsequent events to be triggered without being blocked or delayed due to previous errors.

**Steps to Reproduce:**

1. Set up a Hatchet instance and worker(s) listening for a specific event key (e.g., test:event).
2. Run the attached test.ts script which attempts to trigger the same event using both hatchet.api.eventCreate and hatchet.events.push.
3. Observe the console output for errors when hatchet.api.eventCreate is called.
4. Check the Hatchet dashboard to see if workflows are triggered consistently by both methods.
5. Potentially run the API call multiple times in succession to observe if subsequent calls are blocked after an initial 500 error.

test.ts
```javascript import { hatchet } from "../hatchet-client";

// Define a common event structure
const tenantId = hatchet.tenantId; // Assuming hatchet client is initialized correctly
const eventKey = "test:event-comparison";
const eventPayload = {
  object_type: "comparison_test",
  object_uuid: `test-uuid-${Date.now()}`,
  trigger_method: "", // Will be set dynamically
  timestamp: new Date().toISOString(),
};

async function triggerViaApi(payload: object) {
  console.log(`\n--- Attempting event push via REST API for ${eventKey} ---`);
  try {
    const apiPayload = {
      key: eventKey,
      data: payload,
    };
    // NOTE: We are assuming tenantId is correctly inferred or managed by the SDK/client instance
    // If direct tenantId passing is needed, adjust the API call structure based on SDK specifics.
    await hatchet.api.eventCreate(tenantId, apiPayload);

    // IMPORTANT: Even if the above line doesn't throw an error visible here,
    // monitor the console/network logs for a 500 Internal Server Error response
    // from the Hatchet API endpoint.
    console.log(
      "API eventCreate called successfully (Check console/Hatchet logs for actual server response/errors)."
    );
    console.log("Payload:", JSON.stringify(payload, null, 2));
  } catch (error: any) {
    // This catch block might not always catch the 500 if it's handled internally
    // by the SDK without re-throwing, but it's good practice.
    console.error(
      "Error explicitly caught during API eventCreate call:",
      error.message || error
    );
    if (error.response) {
      console.error("Error Response Data:", error.response.data);
      console.error("Error Response Status:", error.response.status);
    }
  }
}

async function triggerViaGrpc(payload: object) {
  console.log(`\n--- Attempting event push via gRPC for ${eventKey} ---`);
  try {
    // Assuming `hatchet.events.push` correctly infers the tenant ID
    await hatchet.event.push(eventKey, payload);
    console.log("gRPC event.push called successfully.");
    console.log("Payload:", JSON.stringify(payload, null, 2));
  } catch (error: any) {
    console.error("Error during gRPC event.push call:", error.message || error);
  }
}

async function main() {
  console.log("Starting Hatchet event trigger comparison test...");

  // Test Case 1: Trigger via REST API
  const apiEventPayload = { ...eventPayload, trigger_method: "REST_API" };
  await triggerViaApi(apiEventPayload);

  // Optional: Add a small delay to see if the first API error blocks the second
  console.log("\nWaiting 2 seconds before gRPC call...");
  await new Promise((resolve) => setTimeout(resolve, 2000));

  // Test Case 2: Trigger via gRPC
  const grpcEventPayload = { ...eventPayload, trigger_method: "gRPC" };
  await triggerViaGrpc(grpcEventPayload);

  // Optional: Add another API call to test blocking
  console.log("\nWaiting 2 seconds before second API call...");
  await new Promise((resolve) => setTimeout(resolve, 2000));
  const apiEventPayload2 = {
    ...eventPayload,
    object_uuid: `test-uuid-${Date.now()}`,
    trigger_method: "REST_API_2",
  };
  await triggerViaApi(apiEventPayload2);

  console.log("\nTest finished. Check console logs and Hatchet dashboard.");
}

if (require.main === module) {
  main().catch(console.error);
}
```

**Comment by grutt** [comment]
Thanks for the detailed report @AmoonPod 
Are you running against a self host instance or hatchet cloud? If self host, are you seeing the 500 error in the engine logs?

**Comment by AmoonPod** [comment]
> Thanks for the detailed report @AmoonPod 
> Are you running against a self host instance or hatchet cloud? If self host, are you seeing the 500 error in the engine logs?

I'm running a self-hosted instance.
I don't see the the 500 error in the engine logs, but I get it the script I'm using to send events to hatchet.

**Comment by grutt** [comment]
To confirm you're looking in the API pod logs? 

We log all errors by default so I'd be very surprised if there's no details here.

**Comment by AmoonPod** [comment]
I confirm that I'm not getting any error on the logs.

**Comment by grutt** [comment]
I thought this might be related to #1534 but since you're saying the first event does not 500, this is likely not the cause.

Since 500 is a server-side error, this indicates something is wrong with the API or Engine.

Can you share more about how you're self hosting hatchet (docker-compose, k8s, etc)

**Comment by AmoonPod** [comment]
I'm using official docker-compose.yml, with the changes indicated in [https://github.com/hatchet-dev/hatchet/issues/1534#issuecomment-2797227680](https://github.com/hatchet-dev/hatchet/issues/1534#issuecomment-2797227680) and [https://github.com/hatchet-dev/hatchet/issues/1534#issuecomment-2798791169](https://github.com/hatchet-dev/hatchet/issues/1534#issuecomment-2798791169)

**Comment by AndryHTC** [comment]
I've have the same issue, that what I mean in this issue https://github.com/hatchet-dev/hatchet/issues/1521#issue-2985998022
> hatchet.api.eventCreate(...) doesn't give the http2 error, but sometimes gives error 500.

**Comment by grutt** [comment]
Can you try running against [Hatchet Cloud](https://cloud.onhatchet.run/) and report back if you're still seeing the 500 error along with the time when you made the attempt.

**Comment by abelanger5** [comment]
Hey @AndryHTC @AmoonPod this is fixed in version `v0.60.1` -- thanks for the report!

**Comment by AndryHTC** [comment]
> Hey [@AndryHTC](https://github.com/AndryHTC) [@AmoonPod](https://github.com/AmoonPod) this is fixed in version `v0.60.1` -- thanks for the report!

When will be released?

**Comment by AndryHTC** [comment]
> > Hey [@AndryHTC](https://github.com/AndryHTC) [@AmoonPod](https://github.com/AmoonPod) this is fixed in version `v0.60.1` -- thanks for the report!
> 
> When will be released?

It seems that you forgot to update the **latest** tag in the Docker images

![Image](https://github.com/user-attachments/assets/6e9927ff-6a9a-41ac-97b4-2abf69c9c0cd)
